version: '3'

services:
  event-management-database:
    image: mysql:8.0.2
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: event_password
      MYSQL_DATABASE: event_managment
    ports:
      - "3308:3306"
    networks:
      - backend

  event-management-recourse-server:
    restart: always
    image: ragulan28/event-management-recourse-server:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - event-management-database
    networks:
      - backend

  admin:
    image: adminer
    ports:
      - 8081:8080
#    restart: always
    networks:
      - backend
      - frontend


networks:
  backend:
  frontend:
